targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - assets/**
    builders:
      prebuild_code_generator:string_res_builder:
        options:
          # The strings resource path for multi-language.
          input_path:
            en_US: "assets/strings"
          # The directory for the generated code
          output_dir: "lib/res_gen"
          # The default language. It must has a corresponding configuration in [input_path].
          # The default value is "en_US" if not configured.
          default_lang: en_US
