# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:

  string_res_builder:
    import: "package:prebuild_code_generator/builder.dart"
    builder_factories: ["stringResBuilder"]
    build_extensions: {".json": [".g.dart"]}
    build_to: source
    auto_apply: dependents